services:
  bfapi:
    build: .
    volumes:
      - bfapi-data:/opt/bfapi/data
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    stdin_open: true
    tty: true        
    networks:
      - bfapi-network

networks:
  bfapi-network:

volumes:
  bfapi-data:
    driver: local