name: Build and Publish Docker Image
on:
  push:
    branches: [ "docker" ]
env:
  REGISTRY: ghcr.io
jobs:
  build-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build and push AMD64
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ github.repository }}-amd64:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-arm64:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build and push ARM64
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository }}-arm64:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max